services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - 50021:50021
  bot:
    build: .
    image: ghcr.io/yude/zundacord:latest
    env_file:
      - .env
  
